### ISSUE TITLE
undefined symbol: clock_gettime

### ISSUE THREAD

**Issue by benqktc** [mikejsavage/lua-arc4random#1]
dear man, this is wonderful software. thanks for your effort.

i installed it from luarocks. the installation was successful, no error reported.
but when i  use your sample code to test it, i got this error.
[root@QPServerDev ~]# lua test.lua
lua: error loading module 'arc4random' from file '/usr/local/lib/lua/5.3/arc4random.so':
        /usr/local/lib/lua/5.3/arc4random.so: undefined symbol: clock_gettime
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        test.lua:1: in main chunk
        [C]: in ?

i did some search , and add "-lrt" to the LDFLAGS in the makefile, the problem solved.

**Comment by mikejsavage** [comment]
Thanks!
